[package]
name = "maze"
version = "0.1.0"
authors = ["Peter p.milev3@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "*"
bit-vec = "0.6"
lazy_static = "1.4.0"